### ISSUE TITLE
Incomplete line in Council Member Incentives proposal

### ISSUE THREAD

**Issue by ShaperOfEntropy** [VoiNetwork/governance#15]
The following line seems to be incomplete:
https://github.com/VoiNetwork/governance/blob/5798ae8e342f941e9a2dbe1bdba8ea3a6b7e1ef4/Proposal%20Submissions/Council%20Member%20Incentives/CouncilMemberIncentives_VoiFoundation_20230907.md?plain=1#L21

**Comment by BenedictWHD** [comment]
Amazing, thanks for flagging this. Should be resolved now
